---------------------------------------------------------
-- TABELA: USUARIOSGT
---------------------------------------------------------
CREATE TABLE USUARIOSGT (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    SENHA VARCHAR2(60) NOT NULL,
    AREA_ATUACAO VARCHAR2(255) NOT NULL,
    NIVEL_CARREIRA VARCHAR2(255) NOT NULL,
    DATA_CADASTRO DATE NOT NULL
);
---------------------------------------------------------
-- TABELA: USUARIO_ROLES
---------------------------------------------------------
CREATE TABLE USUARIO_ROLES (
    USUARIO_ID NUMBER NOT NULL,
    ROLES VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_USUARIO_ROLES FOREIGN KEY (USUARIO_ID)
        REFERENCES USUARIOSGT(ID)
        ON DELETE CASCADE
);
---------------------------------------------------------
-- TABELA: COMPETENCIAGT
---------------------------------------------------------
CREATE TABLE COMPETENCIAGT (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL UNIQUE,
    CATEGORIA VARCHAR2(50) NOT NULL,
    DESCRICAO VARCHAR2(1000) NOT NULL,
    AREA_CONHECIMENTO VARCHAR2(100) NOT NULL
);
---------------------------------------------------------
-- TABELA: TRILHASGT
---------------------------------------------------------
CREATE TABLE TRILHASGT (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(150) NOT NULL,
    DESCRICAO CLOB NOT NULL,
    NIVEL VARCHAR2(50) NOT NULL,
    CARGA_HORARIA NUMBER NOT NULL,
    FOCO_PRINCIPAL VARCHAR2(255) NOT NULL,
    DATA_CRIACAO DATE,
    CRIADOR_ID NUMBER NOT NULL,
    OBJETIVO_CARREIRA CLOB,
    CONSTRAINT FK_TRILHAS_CRIADOR FOREIGN KEY (CRIADOR_ID)
        REFERENCES USUARIOSGT(ID)
);
---------------------------------------------------------
-- TABELA: TRILHA_COMPETENCIA (MANY-TO-MANY)
---------------------------------------------------------
CREATE TABLE TRILHA_COMPETENCIA (
    TRILHA_ID NUMBER NOT NULL,
    COMPETENCIA_ID NUMBER NOT NULL,
    CONSTRAINT PK_TRILHA_COMPETENCIA PRIMARY KEY (TRILHA_ID, COMPETENCIA_ID),
    CONSTRAINT FK_TC_TRILHA FOREIGN KEY (TRILHA_ID) REFERENCES TRILHASGT(ID),
    CONSTRAINT FK_TC_COMPETENCIA FOREIGN KEY (COMPETENCIA_ID) REFERENCES COMPETENCIAGT(ID)
);
---------------------------------------------------------
-- TABELA: TRILHA_COMPETENCIAGT (ENTIDADE PRÓPRIA)
---------------------------------------------------------
CREATE TABLE TRILHA_COMPETENCIAGT (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRILHA_ID NUMBER NOT NULL,
    COMPETENCIA_ID NUMBER NOT NULL,
    NIVEL_ESPERADO NUMBER,
    CONSTRAINT FK_TTC_TRILHA FOREIGN KEY (TRILHA_ID) REFERENCES TRILHASGT(ID),
    CONSTRAINT FK_TTC_COMPETENCIA FOREIGN KEY (COMPETENCIA_ID) REFERENCES COMPETENCIAGT(ID)
);
---------------------------------------------------------
-- TABELA: MATRICULASGT
---------------------------------------------------------
CREATE TABLE MATRICULASGT (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO_ID NUMBER NOT NULL,
    TRILHA_ID NUMBER NOT NULL,
    DATA_INSCRICAO DATE NOT NULL,
    STATUS VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_MATRICULA_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOSGT(ID),
    CONSTRAINT FK_MATRICULA_TRILHA FOREIGN KEY (TRILHA_ID) REFERENCES TRILHASGT(ID)
);
---------------------------------------------------------
-- TABELA: MATRICULA_COMPETENCIA
---------------------------------------------------------
CREATE TABLE MATRICULA_COMPETENCIA (
    MATRICULA_ID NUMBER NOT NULL,
    COMPETENCIA_ID NUMBER NOT NULL,
    CONSTRAINT PK_MATRICULA_COMPETENCIA PRIMARY KEY (MATRICULA_ID, COMPETENCIA_ID),
    CONSTRAINT FK_MC_MATRICULA FOREIGN KEY (MATRICULA_ID) REFERENCES MATRICULASGT(ID),
    CONSTRAINT FK_MC_COMPETENCIA FOREIGN KEY (COMPETENCIA_ID) REFERENCES COMPETENCIAGT(ID)
);


-- Usuário
INSERT INTO USUARIOSGT (NOME, EMAIL, SENHA, AREA_ATUACAO, NIVEL_CARREIRA, DATA_CADASTRO)
VALUES ('Teste', 'teste@teste.com', 'senha123', 'TI', 'Junior', SYSDATE);

-- Competência
INSERT INTO COMPETENCIAGT (NOME, CATEGORIA, DESCRICAO, AREA_CONHECIMENTO)
VALUES ('Competencia Teste', 'Categoria Teste', 'Descricao Teste', 'TI');

-- Trilha
INSERT INTO TRILHASGT (NOME, DESCRICAO, NIVEL, CARGA_HORARIA, FOCO_PRINCIPAL, CRIADOR_ID)
VALUES ('Trilha Teste', 'Descricao Trilha', 'BASICO', 10, 'Foco Teste', 1);